"""Add Users Table

Revision ID: 195e91fd668a
Revises: 6566a427d78b
Create Date: 2024-01-18 09:40:10.353859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195e91fd668a'
down_revision = '6566a427d78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
